source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'App-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for UIKitApp-UIKit
  pod 'SnapKit'
  pod 'SensorsAnalyticsSDK'
  
  pod 'TUICallKit_Swift', :path=>'../call/TUICallKit_Swift.podspec'
  pod 'TUIRoomKit', :path=>'../room/TUIRoomKit.podspec'
  pod 'TUILiveKit', :path=>'../live/TUILiveKit.podspec'
  pod 'AtomicX', :path=>'../atomic_x/AtomicX.podspec'
  
  pod 'AtomicXCore'
  pod 'Kingfisher'

  pod 'SVGAPlayer', '~> 2.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['GENERATE_INFOPLIST_FILE'] = "NO"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D DEV_MODE'
    end
    shell_script_path = "Pods/Target Support Files/#{target.name}/#{target.name}-frameworks.sh"
    if File::exist?(shell_script_path)
      shell_script_input_lines = File.readlines(shell_script_path)
      shell_script_output_lines = shell_script_input_lines.map { |line| line.sub("source=\"$(readlink \"${source}\")\"", "source=\"$(readlink -f \"${source}\")\"") }
      File.open(shell_script_path, 'w') do |f|
        shell_script_output_lines.each do |line|
          f.write line
        end
      end
    end
  end
end
